export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';  
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_PROFILE = 'GET_PROFILE';
export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_RECENTACTIVITIES='GET_RECENTACTIVITIES'
export const GET_STUD_NAME='GET_STUD_NAME'
export const GET_APPLICATION_COUNT='GET_APPLICATION_COUNT'
<<<<<<< HEAD
=======


>>>>>>> 48cb99a2cb798fa960429cd254a6f4fed9a0c8d7















